# Generated by Django 6.0.1 on 2026-01-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Admin', 'admin'), ('Manager', 'manager'), ('Sales', 'sales'), ('Support', 'support')], default='Sales', max_length=255),
        ),
    ]
