# Generated by Django 6.0.1 on 2026-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_role_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='actions',
            field=models.JSONField(default=list),
        ),
    ]
