# Generated by Django 6.0.1 on 2026-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_deal_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('Open', 'open'), ('Won', 'won'), ('Lost', 'lost'), ('Closed', 'closed')], default='Open', max_length=255),
        ),
    ]
