# Generated by Django 6.0.1 on 2026-01-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_lead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='owner',
            new_name='assigned_to',
        ),
    ]
