"""
Django settings for CRM project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import cloudinary	
from urllib.parse import parse_qsl, unquote, urlparse
from dotenv import load_dotenv

load_dotenv()


DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$d&o6)_xkwd++sb0c+*932&gzk1l-f$cahyls2+=!xw8iop-_y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')
GEMINI_MODEL = os.getenv("GEMINI_MODEL")
EMBED_MODEL= os.getenv('EMBED_MODEL')

TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'user_auth',
    'lead',
    'customer',
    'deal',
    'cloudinary',
    'chat',
    'knowledgbase',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 1,
    'DEFAULT_PERMISSION_CLASSES': [
        'user_auth.permissions.HasPermissions',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# Cloudinary configuration
cloudinary.config( 
  	cloud_name = os.getenv('CLOUD_NAME'),
  	api_key = os.getenv('API_KEY'),
  	api_secret = os.getenv('API_SECRET')
)


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

AUTH_USER_MODEL = 'user_auth.User'

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CRM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CRM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

NEON_DB = os.environ.get('NEON_DB')

if not NEON_DB:
    raise RuntimeError('NEON_DB must be set to the Neon PostgreSQL connection string.')

neon_url = urlparse(NEON_DB)
if neon_url.scheme not in {'postgres', 'postgresql'} or not neon_url.hostname or not neon_url.path:
    raise RuntimeError('NEON_DB must be a valid PostgreSQL connection string.')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': neon_url.path.lstrip('/'),
        'USER': unquote(neon_url.username or ''),
        'PASSWORD': unquote(neon_url.password or ''),
        'HOST': neon_url.hostname,
        'PORT': neon_url.port or 5432,
        # Preserve Neon options such as sslmode=require from its connection URL.
        'OPTIONS': dict(parse_qsl(neon_url.query, keep_blank_values=True)),
        'CONN_MAX_AGE': 600,
    }
}

from langchain_chroma import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings

embed_model = GoogleGenerativeAIEmbeddings(model=str(EMBED_MODEL))
vector_store = Chroma(embedding_function=embed_model, persist_directory="VectorDB")


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

ALLOWED_HOSTS = ['*']

# Frontend origins allowed to call the API from a browser.
CORS_ALLOWED_ORIGINS = [
    'https://connect-crm-suite.vercel.app',
    'https://preview--ims.lovable.app',
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:5500',
    'http://localhost:5500',
    'http://192.168.0.222:3000',
    'http://192.168.0.97:3000',
]

# Required for unsafe (POST/PUT/PATCH/DELETE) requests that use Django's
# session/CSRF authentication from the deployed frontend.
CSRF_TRUSTED_ORIGINS = [
    'https://connect-crm-suite.vercel.app',
]
